server:
  port: 8084

spring:
  datasource:
    mysql: # 默认数据源，Mysql
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://xx.xx.xx.xx/data_warehouse/?useSSL=false&serverTimeZone=UTC
      username: xxx
      password: xxx
      type: com.alibaba.druid.pool.DruidDataSource
    hive: # hive数据源配置
      driver-class-name: org.apache.hive.jdbc.HiveDriver
      jdbc-url: jdbc:hive2://192.168.40.133:10000/data_warehouse
      username: root
      password: hadoop
      type: com.alibaba.druid.pool.DruidDataSource

    druid:
      connect-timeout: 10000

mybatis:
  type-aliases-package: com.tongji.entity
  mapper-locations: classpath*:com/tongji/mapper/*/*.xml

org:
  neo4j:
    driver:
      authentication:
        password: xxxx
        username: xxx
      uri: bolt://xxx.xxx.xxx.xxx:7687

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    sql: debug
    com.tongji.mapper: debug
